# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_localization', models.AutoField(db_column='idLocalizacao', primary_key=True, serialize=False)),
                ('district', models.ForeignKey(db_column='idDistrito', on_delete=django.db.models.deletion.DO_NOTHING, to='district.District')),
                ('specie', models.ForeignKey(db_column='idEspecie', on_delete=django.db.models.deletion.DO_NOTHING, to='species.Specie')),
            ],
            options={
                'db_table': 'localizacaoespecie',
                'managed': True,
                'unique_together': {('id_localization', 'district', 'specie')},
            },
        ),
    ]
