# Generated by Django 2.2.7 on 2019-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_localization', models.AutoField(db_column='idLocalizacao', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'localizacaoespecie',
                'managed': False,
            },
        ),
    ]
