# Generated by Django 2.2.7 on 2019-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idclasse', models.AutoField(db_column='idClasse', primary_key=True, serialize=False)),
                ('classe', models.CharField(db_column='Classe', max_length=45)),
            ],
            options={
                'db_table': 'classe',
                'managed': False,
            },
        ),
    ]
