# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idclasse', models.AutoField(db_column='idClasse', primary_key=True, serialize=False)),
                ('classe', models.CharField(db_column='Classe', max_length=45)),
                ('idfilo', models.ForeignKey(blank=True, db_column='idFilo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filo.Filo')),
            ],
            options={
                'db_table': 'classe',
                'managed': True,
            },
        ),
    ]
