# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id_province', models.AutoField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('province', models.CharField(db_column='Provincia', max_length=45)),
                ('region', models.ForeignKey(db_column='idRegiao', on_delete=django.db.models.deletion.DO_NOTHING, to='region.Region')),
            ],
            options={
                'db_table': 'provincia',
                'managed': True,
            },
        ),
    ]
