# Generated by Django 2.2.7 on 2019-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idfamilia', models.AutoField(db_column='idFamilia', primary_key=True, serialize=False)),
                ('familia', models.CharField(db_column='Familia', max_length=45)),
            ],
            options={
                'db_table': 'familia',
                'managed': False,
            },
        ),
    ]
