# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idfamilia', models.AutoField(db_column='idFamilia', primary_key=True, serialize=False)),
                ('familia', models.CharField(db_column='Familia', max_length=45)),
                ('idordem', models.ForeignKey(blank=True, db_column='idOrdem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordem.Ordem')),
            ],
            options={
                'db_table': 'familia',
                'managed': True,
            },
        ),
    ]
