# Generated by Django 2.2.7 on 2020-10-17 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id_geometry', models.AutoField(db_column='idgeo', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=1000, null=True)),
                ('location', django.contrib.gis.db.models.fields.MultiPointField(db_column='location', srid=4326)),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=2, max_digits=100)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=2, max_digits=100)),
                ('specie', models.ForeignKey(blank=True, db_column='idEspecie', on_delete=django.db.models.deletion.DO_NOTHING, to='species.Specie')),
            ],
            options={
                'db_table': 'geography',
                'managed': True,
            },
        ),
    ]
