# Generated by Django 2.2.7 on 2019-11-13 05:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id_geometry', models.IntegerField(db_column='idgeo', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=45, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_column='location', srid=4326)),
            ],
            options={
                'db_table': 'geography',
                'managed': False,
            },
        ),
    ]
