# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('idordem', models.AutoField(db_column='idOrdem', primary_key=True, serialize=False)),
                ('ordem', models.CharField(db_column='Ordem', max_length=45)),
                ('idclasse', models.ForeignKey(blank=True, db_column='idClasse', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classe.Classe')),
            ],
            options={
                'db_table': 'ordem',
                'managed': True,
            },
        ),
    ]
