# Generated by Django 2.2.7 on 2019-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('idordem', models.AutoField(db_column='idOrdem', primary_key=True, serialize=False)),
                ('ordem', models.CharField(db_column='Ordem', max_length=45)),
            ],
            options={
                'db_table': 'ordem',
                'managed': False,
            },
        ),
    ]
