# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(db_column='idPessoa', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Nome', max_length=45)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': True,
            },
        ),
    ]
