# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(db_column='genero', max_length=45)),
                ('idfamilia', models.ForeignKey(blank=True, db_column='idFamilia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='familia.Familia')),
            ],
            options={
                'db_table': 'genero',
                'managed': True,
            },
        ),
    ]
