# Generated by Django 2.2.7 on 2019-11-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(db_column='Genero', max_length=45)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
    ]
