# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filo',
            fields=[
                ('idfilo', models.AutoField(db_column='idFilo', primary_key=True, serialize=False)),
                ('filo', models.CharField(db_column='Filo', max_length=45)),
                ('idreino', models.ForeignKey(blank=True, db_column='idReino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reino.Reino')),
            ],
            options={
                'db_table': 'filo',
                'managed': True,
            },
        ),
    ]
