# Generated by Django 2.2.7 on 2019-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filo',
            fields=[
                ('idfilo', models.AutoField(db_column='idFilo', primary_key=True, serialize=False)),
                ('filo', models.CharField(db_column='Filo', max_length=45)),
            ],
            options={
                'db_table': 'filo',
                'managed': False,
            },
        ),
    ]
