# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(db_column='idRegiao', primary_key=True, serialize=False)),
                ('region', models.CharField(db_column='Regiao', max_length=45)),
            ],
            options={
                'db_table': 'regiao',
                'managed': True,
            },
        ),
    ]
