# Generated by Django 2.2.7 on 2019-11-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_person', models.ForeignKey(db_column='idPessoa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='person.Person')),
            ],
            options={
                'db_table': 'quemencontrou',
                'managed': False,
            },
        ),
    ]
