# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('person', models.OneToOneField(db_column='idPessoa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='person.Person')),
                ('specie', models.ForeignKey(db_column='idEspecie', on_delete=django.db.models.deletion.DO_NOTHING, to='species.Specie')),
            ],
            options={
                'db_table': 'quemidentificou',
                'managed': True,
                'unique_together': {('person', 'specie')},
            },
        ),
    ]
