# Generated by Django 2.2.7 on 2019-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id_district', models.AutoField(db_column='idDistrito', primary_key=True, serialize=False)),
                ('district', models.CharField(db_column='Distrito', max_length=45)),
            ],
            options={
                'db_table': 'distrito',
                'managed': False,
            },
        ),
    ]
