# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id_district', models.AutoField(db_column='idDistrito', primary_key=True, serialize=False)),
                ('district', models.CharField(db_column='Distrito', max_length=45)),
                ('province', models.ForeignKey(db_column='idProvincia', on_delete=django.db.models.deletion.DO_NOTHING, to='province.Province')),
            ],
            options={
                'db_table': 'distrito',
                'managed': True,
            },
        ),
    ]
