# Generated by Django 2.2.7 on 2019-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id_specie', models.AutoField(db_column='idEspecie', primary_key=True, serialize=False)),
                ('specie', models.CharField(blank=True, db_column='Especie', max_length=45, null=True)),
                ('habitat', models.CharField(blank=True, db_column='Habitat', max_length=1000, null=True)),
                ('detail', models.CharField(blank=True, db_column='detalhes', max_length=1000, null=True)),
                ('common_name', models.CharField(blank=True, db_column='NomeComum', max_length=45, null=True)),
                ('date_created', models.DateTimeField(db_column='DataCriacao')),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
    ]
