# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id_specie', models.AutoField(db_column='idspecie', primary_key=True, serialize=False)),
                ('specie', models.CharField(blank=True, db_column='specie', max_length=45, null=True)),
                ('habitat', models.CharField(blank=True, db_column='Habitat', max_length=1000, null=True)),
                ('detail', models.CharField(blank=True, db_column='detalhes', max_length=1000, null=True)),
                ('common_name', models.CharField(blank=True, db_column='NomeComum', max_length=45, null=True)),
                ('date_created', models.DateTimeField(db_column='DataCriacao')),
                ('gender', models.ForeignKey(blank=True, db_column='idGenero', on_delete=django.db.models.deletion.DO_NOTHING, to='genero.Genero')),
            ],
            options={
                'db_table': 'specie',
                'managed': True,
            },
        ),
    ]
