# Generated by Django 2.2.7 on 2021-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='specie_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='specie',
            name='threat',
            field=models.TextField(blank=True, db_column='ameacas', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='year',
            field=models.IntegerField(db_column='ano', default=1),
            preserve_default=False,
        ),
    ]
