# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reino',
            fields=[
                ('idreino', models.AutoField(db_column='idreino', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='reino', max_length=200)),
            ],
            options={
                'db_table': 'reino',
                'managed': False,
            },
        ),
    ]
