# Generated by Django 2.2.7 on 2019-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reino',
            fields=[
                ('idreino', models.AutoField(db_column='idReino', primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'reino',
                'managed': False,
            },
        ),
    ]
